-- 4. Вывести названия фильмов, которых нет в inventory.
-- Написать запрос без использования оператора IN.

SELECT film.title
FROM film
    LEFT JOIN inventory ON film.film_id = inventory.film_id
WHERE inventory.inventory_id IS NULL;

--          title
-- ------------------------
--  SKY MIRACLE
--  KILL BROTHERHOOD
--  SISTER FREDDY
--  GLADIATOR WESTWARD
--  FLOATS GARDEN
--  APOLLO TEEN
--  CRYSTAL BREAKING
--  HOCUS FRIDA
--  FRANKENSTEIN STRANGER
--  RAIDERS ANTITRUST
--  HATE HANDICAP
--  ORDER BETRAYED
--  WAKE JAWS
--  DELIVERANCE MULHOLLAND
--  BUTCH PANTHER
--  PSYCHO SHRUNK
--  CATCH AMISTAD
--  ARK RIDGEMONT
--  CROWDS TELEMARK
--  FIREHOUSE VIETNAM
--  PEARL DESTINY
--  VOLUME HOUSE
--  GUMP DATE
--  ROOF CHAMPION
--  WALLS ARTIST
--  CROSSING DIVORCE
--  MUPPET MILE
--  ARSENIC INDEPENDENCE
--  RAINBOW SHOCK
--  COMMANDMENTS EXPRESS
--  CHOCOLATE DUCK
--  ARGONAUTS TOWN
--  SUICIDES SILENCE
--  KENTUCKIAN GIANT
--  PERDITION FARGO
--  TREASURE COMMAND
--  BOONDOCK BALLROOM
--  ALICE FANTASIA
--  VILLAIN DESPERATE
--  TADPOLE PARK
--  DAZED PUNK
--  CHINATOWN GLADIATOR
-- (42 rows)
