CREATE OR REPLACE TABLE RAW_TABLE (
    _id VARCHAR,
    IOS_App_Id INT,
    Title VARCHAR,
    Developer_Name VARCHAR,
    Developer_IOS_Id FLOAT,
    IOS_Store_Url VARCHAR,
    Seller_Official_Website VARCHAR,
    Age_Rating VARCHAR,
    Total_Average_Rating FLOAT,
    Total_Number_of_Ratings FLOAT,
    Average_Rating_For_Version FLOAT,
    Number_of_Ratings_For_Version INT,
    Original_Release_Date VARCHAR,
    Current_Version_Release_Date VARCHAR,
    Price_USD FLOAT,
    Primary_Genre VARCHAR,
    All_Genres VARCHAR,
    Languages VARCHAR,
    Description VARCHAR
);