CREATE OR REPLACE FILE FORMAT UPDATED_FORMAT_CSV
TYPE = 'CSV'
COMPRESSION = 'GZIP'
SKIP_HEADER=1
NULL_IF = ('NULL', 'null')
FIELD_DELIMITER='^'
RECORD_DELIMITER = '\t'
EMPTY_FIELD_AS_NULL = TRUE
SKIP_HEADER=1
